# Generated by Django 4.0.6 on 2023-10-09 15:01

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_user', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('package_description', models.TextField()),
                ('tracking_id', models.CharField(max_length=10)),
                ('Current_Status', models.TextField(default='Booked')),
                ('booking_date', models.DateField(default=myapp.models.calculate_default_booking_date)),
                ('expected_date', models.DateField(default=myapp.models.calculate_default_expected_date)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='Hi')),
                ('last_name', models.TextField(default='Hi')),
                ('username', models.TextField(default='Hi')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(default='Hi')),
            ],
        ),
    ]
